#!/bin/sh
NOMVM="debian-gr4"
NOMGR="BrGr-4"
ADMINUSER="adminuser"
NOMVNET="vnetgr4"
NOMBASTION="BastionGr4"
NOMDISK="diskgr4"
LOCAL="JapanEast"
az group create --location $LOCAL --name $NOMGR

# az vm wait # permet de mettre en attente la CLI jusqu'a ce qu'une condition soit remplie

# Extention pour avoir toute les commandes et option disponible
# az interactive
# installation SSH    
# az ssh

# COMMANDE DE SUPPRESSION
# az group delete -n BrGr-4
az network vnet create --resource-group $NOMGR --name $NOMVNET --address-prefix 10.0.0.0/16 --subnet-name AzureBastionSubnet --subnet-prefix 10.0.0.0/24 --location $LOCAL
az network public-ip create --resource-group $NOMGR --name ipbastion --sku Standard --allocation-method Static --sku Standard --location $LOCAL
az network public-ip create --resource-group $NOMGR --name ipvm --sku Standard --allocation-method Static --sku Standard --location $LOCAL
BAS=$(az network bastion create --location $LOCAL --name $NOMBASTION --public-ip-address ipbastion --resource-group $NOMGR --vnet-name $NOMVNET)
IDBAST=$(echo $BAS | jq -r ".id")
# CRÉATION DE LA VM  ==> jq -r == | sed -e "s/\"//g") pour enlever les ""
RES=$(az vm create -n $NOMVM -g $NOMGR --image Debian:debian-11:11:latest --generate-ssh-keys --public-ip-sku Standard --admin-username $ADMINUSER --vnet-name $NOMVNET --subnet-address-prefix 10.0.1.0/24 --public-ip-address ipvm --subnet SubVM --location $LOCAL)
IPVM=$(echo $RES | jq -r ".publicIpAddress")
IDVM=$(echo $RES | jq -r ".id")

echo "#######################"
echo "# $IPVM #"
echo "#######################" 

# creation des disques et attachement
az extension add --name ssh
az disk create --name $NOMDISK --resource-group $NOMGR --size-gb 64 --location $LOCAL --encryption-type EncryptionAtRestWithPlatformKey
diskId=$(az disk show -g $NOMGR -n $NOMDISK --query 'id' -o tsv)

az vm disk attach -g $NOMGR --vm-name $NOMVM --name $diskId

# az vm create -n $NOMVM -g $NOMGR --image Debian:debian-11:11:latest --generate-ssh-keys --public-ip-sku Standard --admin-username $ADMINUSER --vnet-name $NOMVNET --public-ip-address ipvm
az vm open-port --port 80 --resource-group $NOMGR --name $NOMVM --priority 155
az vm open-port --port 22 --resource-group $NOMGR --name $NOMVM --priority 158

# connection à la vm avec bastion
SSHVM=$(az sshkey show --ids $IDVM --name $NOMVM -resource-group $NOMGR)

az resource update --ids $IDBAST --set properties.enableTunneling=True
az network bastion ssh --name $NOMBASTION --resource-group $NOMGR --target-resource-id $IDVM --auth-type "ssh-key" --username $ADMINUSER --ssh-key $SSHVM

# activer le tunneling dans bastion
# az resource update --ids <bastion resource ids> --set properties.enableTunneling=True

# connection à la vm
# ssh azureuser@$IPVM 
# sudo apt update && apt -y upgrade
# apt install default-jdk
# créeation d'un utilisateur tomcat et installation apache tomcat
# groupadd tomcat
# useradd -g tomcat -d /opt/tomcat -s /bin/nologin tomcat

# sudo apt -y install tomcat9 tomcat9-admin


